version: 2.1
orbs:
  python: circleci/python@1.4.0
############
# Workflows
############
workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master

##################
# Job Definitions
##################
jobs:
  build:
    working_directory: ~/Webapplications
    docker:
      - image: circleci/python:3.9.2-browsers
    steps:
      - checkout
      - run:
           command: |
             python3 -m venv venv
             . venv/bin/activate
             pip install -r requirements.txt
             python3 app/app.py &
             ps | grep app.py
  test:
    working_directory: ~/Webapplications
    docker:
      - image: circleci/python:3.9.2-browsers
    steps:
      - checkout 
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - restore_cache:
          key: deps2-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps2-{{ checksum "requirements.txt" }}
          paths:
            - 'venv'
      - run:
          command: |
            . venv/bin/activate
            python3 tests/test.py
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/

    